In [2]:
import numpy as np
import pandas
from sklearn.svm import SVC

In [3]:
train= np.genfromtxt('svm-data.csv', delimiter=',')

In [5]:
train_target = train[:,0]
train_features = train[:,1:]

In [6]:
svc = SVC(C=100000,random_state=241)

In [7]:
svc.fit(train_features, train_target)

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=241, shrinking=True,
  tol=0.001, verbose=False)

In [8]:
svc.support_ + 1

array([ 4,  5, 10])

In [9]:
train_features

array([[0.7 , 0.29],
       [0.23, 0.55],
       [0.72, 0.42],
       [0.98, 0.68],
       [0.48, 0.39],
       [0.34, 0.73],
       [0.44, 0.06],
       [0.4 , 0.74],
       [0.18, 0.18],
       [0.53, 0.53]])

In [4]:
train

array([[0.  , 0.7 , 0.29],
       [1.  , 0.23, 0.55],
       [0.  , 0.72, 0.42],
       [0.  , 0.98, 0.68],
       [0.  , 0.48, 0.39],
       [1.  , 0.34, 0.73],
       [0.  , 0.44, 0.06],
       [1.  , 0.4 , 0.74],
       [0.  , 0.18, 0.18],
       [1.  , 0.53, 0.53]])